export class SfntError extends Error {}
class Reader { constructor(readonly b:Uint8Array){} u8(o:number){if(o<0||o>=this.b.length)throw new SfntError(`读越界 @${o}`);return this.b[o]} u16(o:number){return this.u8(o)*256+this.u8(o+1)} i16(o:number){const v=this.u16(o);return v&0x8000?v-65536:v} u32(o:number){return this.u16(o)*65536+this.u16(o+2)} }
export interface SfntTable {tag:string;offset:number;length:number;checksum:number}
export class Sfnt { readonly tables:Map<string,SfntTable>; constructor(readonly bytes:Uint8Array){const r=new Reader(bytes);if(bytes.length<12)throw new SfntError("文件太短");const v=r.u32(0);if(v===0x4f54544f)throw new SfntError("CFF 字体不支持");if(v!==0x10000&&v!==0x74727565&&v!==0x74797031)throw new SfntError("不是 TrueType 字体");const n=r.u16(4);if(!n||n>512)throw new SfntError("表目录异常");this.tables=new Map();for(let i=0;i<n;i++){const p=12+i*16,tag=String.fromCharCode(...bytes.slice(p,p+4)),off=r.u32(p+8),len=r.u32(p+12);if(off+len>bytes.length)throw new SfntError(`表 ${tag} 越界`);this.tables.set(tag,{tag,offset:off,length:len,checksum:r.u32(p+4)});}}
 need(t:string){const x=this.tables.get(t);if(!x)throw new SfntError(`缺表 ${t}`);return x} slice(t:SfntTable){return this.bytes.slice(t.offset,t.offset+t.length)} numGlyphs(){return new Reader(this.slice(this.need("maxp"))).u16(4)} numHMetrics(){return new Reader(this.slice(this.need("hhea"))).u16(34)} headInfo(){const r=new Reader(this.slice(this.need("head")));return [r.u16(18),r.i16(50)] as const}
 cmap(){const b=this.slice(this.need("cmap")),r=new Reader(b),n=r.u16(2);let best=-1,rank=-1;for(let i=0;i<n;i++){const p=4+i*8,pl=r.u16(p),en=r.u16(p+2),o=r.u32(p+4),f=r.u16(o),q=pl===3&&en===10&&f===12?4:pl===3&&en===1&&f===4?3:pl===0&&f===12?2:pl===0&&f===4?1:-1;if(q>rank){rank=q;best=o}}if(best<0)throw new SfntError("没有 Unicode cmap");return r.u16(best)===4?this.cmap4(b,best):this.cmap12(b,best)}
 private cmap4(b:Uint8Array,o:number){const r=new Reader(b),sx=r.u16(o+6),seg=sx/2,eb=o+14,sb=eb+sx+2,db=sb+sx,rb=db+sx,out=new Map<number,number>();for(let i=0;i<seg;i++){const e=r.u16(eb+i*2),s=r.u16(sb+i*2),d=r.u16(db+i*2),ro=r.u16(rb+i*2);if(s>e||s===0xffff)continue;for(let c=s;c<=e;c++){const g=ro===0?(c+d)&65535:r.u16(rb+i*2+ro+2*(c-s));if(g)out.set(c,(g+d)&65535)}}return out}
 private cmap12(b:Uint8Array,o:number){const r=new Reader(b),n=r.u32(o+12),out=new Map<number,number>();for(let i=0;i<n;i++){const p=o+16+i*12,s=r.u32(p),e=r.u32(p+4),g=r.u32(p+8);for(let c=s;c<=e&&c<=65535;c++)out.set(c,g+c-s)}return out}
 locaOffsets(){const n=this.numGlyphs(),r=new Reader(this.slice(this.need("loca"))),fmt=this.headInfo()[1],o:number[]=[];for(let i=0;i<=n;i++)o.push(fmt===0?r.u16(i*2)*2:r.u32(i*4));return o}
}
